### ISSUE TITLE
👷🏼 Remove publish-gh-pages workflow

### ISSUE THREAD

**Issue by ccamel** [okp4/ontology#207]
## Idea

Remove the `publish-gh-pages` workflow that currently handles the deployment of the ontology's documentation site to GitHub Pages. Following the implementation of issues #76 and #111, the documentation will now be generated in markdown format and subsequently integrated into the [OKP4 documentation website](https://docs.okp4.network/).

## Todo

- [x] Remove any reference to `https://ontology.okp4.space/`
- [x] Remove workflow `publish-gh-pages`
- [x] ~~Remove branch `gh-pages` and associated deployment~~ branch `gh-pages` is now used to publish the ontology sources only (not the documentation - cf. https://github.com/okp4/ontology/issues/214)
