### ISSUE TITLE
♻️ Transition to `w3id.org` URIs

### ISSUE THREAD

**Issue by ccamel** [okp4/ontology#215]
## Context

Currently, our ontology utilizes a series of URIs under the domain `ontology.okp4.space`. These URIs encompass various aspects of our ontology, including thesauri and verifiable credentials schemas For information, the specific URIs in use are:

- `https://ontology.okp4.space/thesaurus`
- `https://ontology.okp4.space/thesaurus/topic`
- `https://ontology.okp4.space/thesaurus/media-type`
- `https://ontology.okp4.space/thesaurus/license`
- `https://ontology.okp4.space/thesaurus/digital-service-digital-service-execution-status`
- `https://ontology.okp4.space/thesaurus/digital-service-category`
- `https://ontology.okp4.space/thesaurus/area`
- `https://ontology.okp4.space/schema/credential/zone/declaration`
- `https://ontology.okp4.space/schema/credential/governance/text`
- `https://ontology.okp4.space/schema/credential/digital-service/execution-proof`
- `https://ontology.okp4.space/schema/credential/digital-service/execution-order`
- `https://ontology.okp4.space/schema/credential/digital-service/description`
- `https://ontology.okp4.space/schema/credential/digital-service/declaration`
- `https://ontology.okp4.space/schema/credential/digital-resource/zone/description`
- `https://ontology.okp4.space/schema/credential/digital-resource/rights`
- `https://ontology.okp4.space/schema/credential/digital-resource/declaration`
- `https://ontology.okp4.space/schema/credential/digital-resource/dataset/description`

## Issue

When selecting URIs to represent the namespaces of an ontology's resources, it's essential that they have several key characteristics:

- _Stability_: The URIs should be stable, meaning they must remain constant over time. This ensures that once a resource is defined, its identifier doesn't change, which is crucial for maintaining consistent references in databases and applications that use the ontology.
- _Versioning Capability_: They should be capable of versioning, allowing for the tracking of changes and updates over time. Versioned URIs enable users to understand and manage the evolution of the ontology, ensuring that changes are transparent and traceable.
- _Resolvability_: The URIs need to be resolvable, which means that they can be accessed and retrieved over the web. Resolvable URIs ensure that users can easily locate and access the resources they refer to, facilitating the practical use and integration of the ontology in various (semantic) web2-3 applications.

The current `https://ontology.okp4.space/` URI scheme has shortcomings:

- _Stability Concerns_: The URIs might not stay reliable over time, especially if there are changes in where they are hosted.
- _Limited Redirect Flexibility_: This scheme doesn't offer much control over redirecting URIs, which can be problematic if the location of the resources changes.

## Proposal

The proposal is to transition the URIs used in our ontology from `ontology.okp4.space` to `w3id.org/okp4/ontology`. This change is aimed at:
- ensure persistent and stable URIs for our ontology.
- enhance the reliability and accessibility of our ontology.
- align with best practices in the semantic web community.

The [w3id.org](https://w3id.org/) service provides _reliable_, _permanent identifiers_, which is crucial for the long-term usability and citation of our ontology in various (semantic) web2-3 applications.

Adopting this service will enable straightforward URI redirection during resolution:

> `https://w3id.org/okp4/ontology/<path>` →  `https://ontology.okp4.space/<path>`

## Todo

- [x] Update all references from `ontology.okp4.space` to `w3id.org/okp4/ontology` within the ontology.
- [x] Update all related documentation and examples accordingly.
- [x] Wait for #216 to be implemented. 
- [x] Register the `w3id.org/okp4/ontology` identifier in `w3id.org` and specify the redirection:
  - [x] Fork the [w3id.org GitHub repository](https://github.com/perma-id/w3id.org)
  - [x] Create the new identifier `okp4`
  - [x] Adds a `.htaccess` file with the necessary rewrite rules to redirect from `w3id.org/okp4/ontology/<path>` to our current ontology hosting location `ontology.okp4.space/<path>`
  - [x] Adds a `readme.md` with description and contact info
- [x] Create and submit the Pull Request to `w3id.org` Repository
- [x] Wait for merge
- [x] Test redirections

**Comment by MdechampG** [comment]
Good improvement 👍🏻  I can contribute on the 2 first tasks if you want.

**Comment by ccamel** [comment]
@MdechampG Great! Would be greatly appreciated :+1:

**Comment by ccamel** [comment]
PR submitted to`w3id.org` Repository - <https://github.com/perma-id/w3id.org/pull/3771>.

**Comment by ccamel** [comment]
Okay. Works fine.

Some tests:

```
curl -sD - -o /dev/null https://w3id.org/okp4/ontology/vnext/thesaurus/digital-service-category/ClusteringModel/FooBar.html | grep Location
Location: https://docs.okp4.network/technical-documentation/ontology/the-power-of-ontologies

curl -sD - -o /dev/null https://w3id.org/okp4/ontology/vnext/thesaurus/digital-service-category/FooBar.ttl | grep Location
Location: https://ontology.okp4.space/vnext/thesaurus/digital-service-category.ttl

curl -sD - -o /dev/null https://w3id.org/okp4/ontology/vnext/schema/credential/governance/text/FooBar.jsonld | grep Location
Location: https://ontology.okp4.space/vnext/schema/governance/credential-governance-text.jsonld

curl -H "accept: application/ld+json" -sD - -o /dev/null https://w3id.org/okp4/ontology/vnext/schema/credential/governance/text/FooBar | grep Location
Location: https://ontology.okp4.space/vnext/schema/governance/credential-governance-text.jsonld
```
