### ISSUE TITLE
📄 Generate documentation for ontology in markdown format

### ISSUE THREAD

**Issue by ccamel** [okp4/ontology#76]
## Purpose

As a OKP4 builder, I would like to have a comprehensive documentation of the ontology, so that I can easily understand the concepts, relationships, and properties defined in the ontology. This documentation is commited in the project.

The idea is that the generated documentation is then aggregated in the [OKP4 docusaurus documentation site](https://github.com/okp4/docs), as is already done for the [okp4d](https://github.com/okp4/okp4d) and [contracts](https://github.com/okp4/contracts) projects.

## Todo

- [ ] Implement the generation of the markdown version of the ontology, using for instance [python](https://www.python.org/) and [rdflib](https://rdflib.readthedocs.io/en/stable/):
  - [x] Organize the documentation in a clear and concise manner, with sections for the ontology's purpose, classes, properties, and relationships on one side, and on the other side the vocabularies expressed in [SKOS](https://www.w3.org/2004/02/skos/).
  - [x] This feature should be added as a new target in the Makefile. 
- [ ] Use the diagrams generated (implemented by #111)
- [x] Integrate a CI job to verify that the generated documentation is always up-to-date with the latest version of the ontology.
- [x] Include instructions for users in the repository's README on how to generate the documentation.

**Comment by ccamel** [comment]
This issue is starting to become urgent because the ontology is becoming increasingly substantial, and we need documentation support and schemas to fully understand it. This is necessary for the front-end developers, blockchain developers, product team, and marketing communications.

**Comment by ccamel** [comment]
I have separated the generation of the actual images in another ticket #111.

**Comment by ChaimaaZaoui** [comment]
@ccamel can you tell me if this ticket has started ? urgent one month ago ? should I re-prioritise it ?

**Comment by ccamel** [comment]
@ChaimaaZaoui This ticket is indeed urgent, as there is an urgent need for the most complete possible documentation for developers and builders, in line with @antho31's  initiatives on this subject.
